// The canonical set of command ids the app can dispatch. The renderer's command
// registry (renderer/src/commands.ts) owns the rich metadata — title, group,
// key hint, and the run function; this is the flat id list, shared so the main
// process can validate a keybindings file and answer the MCP `list_commands`
// tool without importing renderer code.
//
// The two are held in lockstep by registry.test.ts, in both directions: a
// command missing here is one the user cannot bind and Claude cannot see, and
// an id here with no command behind it is a tool call that fails at runtime.

export const COMMAND_IDS: string[] = [
  // Panels
  'panel.right',
  'panel.left',
  'panel.down',
  'panel.up',
  'panel.focusAt',
  'panel.close',
  'panel.dock',
  'panel.grow',
  'panel.shrink',
  'panel.resetSize',
  'panel.goto',
  // Cursor
  'cursor.down',
  'cursor.up',
  'cursor.top',
  'cursor.bottom',
  'cursor.halfDown',
  'cursor.halfUp',
  'find.open',
  'find.next',
  'find.prev',
  'bash.copy',
  'bash.run',
  'files.expand',
  'files.rename',
  'files.move',
  'files.delete',
  'editor.open',
  'files.collapse',
  'scroll.down',
  'scroll.up',
  // Chat
  'composer.focus',
  'composer.leave',
  // Diff
  'selection.toggle',
  'selection.cancel',
  'selection.comment',
  // App
  'palette.chord',
  'palette.open',
  'palette.commands',
  'palette.files',
  'project.add',
  'project.move',
  'project.delete',
  'project.move.start',
  'project.move.up',
  'project.move.down',
  'project.move.commit',
  'project.move.cancel',
  'group.create',
  'group.delete',
  'auth.account',
  'settings.open',
  'commands.open',
  'skills.open',
  'skill.new',
  'skill.rename',
  'skill.delete',
  'skill.edit',
  'mcp.install',
  'mcp.open',
  'mcp.new',
  'mcp.edit',
  'mcp.toggle',
  'mcp.auth',
  'mcp.delete',
  'keybindings.reset',
  'update.check',
  'update.install',
  // Sessions & worktrees
  'session.prev',
  'session.next',
  'session.alternate',
  'session.new',
  'session.delete',
  'session.deleteOthers',
  'session.deleteAll',
  'worktree.new',
  'worktree.merge',
  'merge.confirm',
  'merge.review',
  'merge.stash',
  'merge.cancel',
  // Commands (the worktree's registered processes)
  'command.run',
  'command.stop',
  'command.restart',
  'command.logs',
  'command.runAll',
  'command.stopAll',
  'command.add',
  'command.edit',
  'command.rename',
  'command.scope',
  'command.delete'
]

export const COMMAND_ID_SET = new Set(COMMAND_IDS)
