// The canonical set of command ids the app can dispatch. The renderer's command
// registry (renderer/src/commands.ts) owns the rich metadata — title, group,
// key hint, and the run function; this is the flat id list, shared so the main
// process can validate a keybindings file and answer the MCP `list_commands`
// tool without importing renderer code.
//
// The two are held in lockstep by registry.test.ts, in both directions: a
// command missing here is one the user cannot bind and Claude cannot see, and
// an id here with no command behind it is a tool call that fails at runtime.

export const COMMAND_IDS: string[] = [
  // Panels
  'panel.right',
  'panel.left',
  'panel.down',
  'panel.up',
  'panel.focusAt',
  'panel.close',
  'panel.dock',
  'panel.grow',
  'panel.shrink',
  'panel.resetSize',
  'panel.goto',
  'browser.open',
  'browser.address',
  'browser.back',
  'browser.forward',
  'browser.reload',
  'browser.stop',
  'browser.focus',
  'browser.devtools',
  'browser.screenshot',
  // Cursor
  'cursor.down',
  'cursor.up',
  'cursor.top',
  'cursor.bottom',
  'cursor.halfDown',
  'cursor.halfUp',
  'find.open',
  'find.next',
  'find.prev',
  'bash.copy',
  'bash.run',
  'bash.preview',
  'files.expand',
  'files.rename',
  'files.move',
  'files.delete',
  'editor.open',
  'file.open',
  'files.collapse',
  'changes.view',
  'files.root',
  'files.unroot',
  'scroll.down',
  'scroll.up',
  // Chat
  'composer.focus',
  'composer.leave',
  // Diff
  'diff.view',
  'diff.nextChange',
  'diff.prevChange',
  'selection.toggle',
  'selection.cancel',
  'selection.comment',
  'code.definition',
  'code.back',
  // App
  'palette.chord',
  'palette.open',
  'palette.commands',
  'help.keys',
  'palette.files',
  'project.add',
  'project.reload',
  'project.move',
  'project.rename',
  'project.delete',
  'project.move.start',
  'project.move.up',
  'project.move.down',
  'project.move.commit',
  'project.move.cancel',
  'group.create',
  'group.delete',
  'auth.account',
  'settings.open',
  'chat.layout',
  'appearance.transparency',
  'commands.open',
  'skills.open',
  'skill.new',
  'skill.rename',
  'skill.delete',
  'skill.edit',
  'skill.favorite',
  'skill.import',
  'draw.open',
  'draw.new',
  'draw.rename',
  'draw.delete',
  'draw.reveal',
  'draw.promote',
  // Colony
  'colony.left',
  'colony.right',
  'colony.start',
  'colony.archive',
  'colony.nanny',
  'colony.new',
  'colony.stages',
  'colony.automerge',
  'colony.report',
  'colony.openReport',
  'support.up',
  'support.down',
  'support.status',
  'support.logs',
  'mcp.install',
  'cli.install',
  'mcp.open',
  'mcp.new',
  'mcp.edit',
  'mcp.toggle',
  'mcp.auth',
  'mcp.delete',
  'composer.vim',
  'keybindings.reset',
  'update.check',
  'update.install',
  // Sessions & worktrees
  'session.prev',
  'session.next',
  'session.alternate',
  'session.new',
  'session.rename',
  'session.delete',
  'session.deleteOthers',
  'session.deleteAll',
  'session.deleteIdle',
  'session.mark',
  'session.markClear',
  'session.deleteMarked',
  'session.unread',
  'session.recap',
  // Queries (a side conversation running beside the chat)
  'query.open',
  'query.focus',
  'query.peek',
  'query.merge',
  'query.discard',
  'query.reopen',
  'query.showAll',
  // The subagent dock (the lanes this chat has working, in its corner)
  'subagents.toggle',
  'chat.all',
  'worktree.new',
  'worktree.focusAt',
  'worktree.merge',
  'merge.confirm',
  'merge.review',
  'merge.stash',
  'merge.cancel',
  'worktree.remove',
  'remove.confirm',
  'remove.cancel',
  'worktree.provision',
  'worktree.premise',
  'provision.confirm',
  'provision.cancel',
  // Project setup (the commands a project gets registered)
  'setup.start',
  'setup.retry',
  'setup.cancel',
  'setup.chat',
  // Commands (the worktree's registered processes)
  'command.run',
  'command.stop',
  'command.restart',
  'command.logs',
  'command.runAll',
  'command.stopAll',
  'command.add',
  'command.edit',
  'command.rename',
  'command.scope',
  'command.delete',
  // Backends (multi-machine attach — see shared/remoteProtocol.ts)
  'backend.use'
]

export const COMMAND_ID_SET = new Set(COMMAND_IDS)
