import { execFile, spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { readSupportConfig } from './compose'

// Per-worktree routing on the shared server. The host runs a single Caddy (built
// with the cloudflare DNS plugin) that fronts everything on the Tailscale IP —
// the Floe UI at `ide.<domain>` and the worktree apps at `<slug>.dev.<domain>`.
// Its Caddyfile (`~/.config/caddy/Caddyfile`) `import`s `sites/*.caddy`, so a
// worktree route is just a file dropped in that dir; `caddy reload` picks it up.
//
// We reuse the host Caddy instead of running our own: it already owns :443 on the
// Tailscale IP with valid wildcard TLS, and it fronts the Floe UI itself, which
// is not a container and so could never be discovered from a container label.
//
// Server-only, and enforced HERE rather than at each call site. Container mode is
// also opt-in on the desktop (`Project.env.mode: 'container'`), where there is no
// host Caddy at all — a route write there would reject and take provisioning down
// with it, before dependencies are even installed. Every entry point below is a
// no-op off the server, and says so by returning false.

const SITES_DIR = join(homedir(), '.config', 'caddy', 'sites')
const CADDYFILE = join(homedir(), '.config', 'caddy', 'Caddyfile')

const routeFile = (host: string): string => join(SITES_DIR, `${host}.caddy`)

/** Whether this Floe is the one that owns the machine's edge. Set by the headless shim. */
export const edgeIsOurs = (): boolean => process.env.FLOE_IS_SERVER === '1'

// `caddy reload` runs in a fresh process, so `{env.CF_API_TOKEN}` in the Caddyfile
// resolves against ITS env — which must carry the token or the cloudflare TLS
// module rejects an empty value and the reload aborts. The running caddy already
// has the token in its environment; read it from there so we don't duplicate the
// secret into support.env. Linux-only (uses /proc); returns '' elsewhere.
function caddyPid(): string {
  return spawnSync('pgrep', ['-x', 'caddy'], { encoding: 'utf8' }).stdout?.trim().split('\n')[0] ?? ''
}

export function caddyToken(): string {
  const pid = caddyPid()
  if (!pid) return ''
  try {
    const environ = readFileSync(`/proc/${pid}/environ`, 'utf8')
    const hit = environ.split('\0').find((l) => l.startsWith('CF_API_TOKEN='))
    return hit ? hit.slice('CF_API_TOKEN='.length) : ''
  } catch {
    return ''
  }
}

// Caddy is commonly a user-local install (`~/.local/bin/caddy` on the server),
// which is NOT on the PATH a systemd unit inherits — `execFile('caddy', …)`
// would ENOENT and every route silently fail to publish. The running Caddy knows
// its own path, so take it from there; the bare name is only the last resort for
// a machine where the reload will fail loudly anyway.
export function caddyBin(): string {
  const pid = caddyPid()
  if (!pid) return 'caddy'
  try {
    return readFileSync(`/proc/${pid}/cmdline`, 'utf8').split('\0')[0] || 'caddy'
  } catch {
    return 'caddy'
  }
}

function reloadCaddy(): Promise<void> {
  return new Promise((resolve, reject) => {
    execFile(
      caddyBin(),
      ['reload', '--config', CADDYFILE],
      // The running Caddy's own token wins; otherwise keep whatever this process
      // was given. Writing the empty string on a /proc miss would strip a token the
      // daemon environment already carries, and the cloudflare module rejects an
      // empty value — turning a missed lookup into a failed reload.
      { env: { ...process.env, CF_API_TOKEN: caddyToken() || process.env.CF_API_TOKEN || '' } },
      (err, _stdout, stderr) => (err ? reject(new Error(stderr.trim() || err.message)) : resolve())
    )
  })
}

// The Caddyfile block for one worktree app: bind the same IP as the main site
// (else Caddy conflicts with itself on :443), per-site DNS-01 TLS, reverse-proxy
// to the loopback port the app container publishes.
// ponytail: per-site cert means a ~30-60s first-request wait while ACME runs;
// swap for a shared `*.dev` wildcard cert if that latency bites.
export function routeBlock(host: string, port: number, bind: string): string {
  return `# Generated by Floe — worktree app route.
${host} {
	bind ${bind}
	tls {
		dns cloudflare {env.CF_API_TOKEN}
		propagation_delay 30s
		propagation_timeout -1
	}
	reverse_proxy 127.0.0.1:${port}
}
`
}

// Add (or rewrite) a route and reload Caddy. Idempotent. Returns whether a route
// was actually published, so callers report the https URL only when it exists.
export async function writeWorktreeRoute(host: string, port: number): Promise<boolean> {
  if (!edgeIsOurs()) return false
  mkdirSync(SITES_DIR, { recursive: true })
  writeFileSync(routeFile(host), routeBlock(host, port, readSupportConfig().edgeBind))
  await reloadCaddy()
  return true
}

// Remove a route and reload. No-op when there is nothing to remove — a
// host-native worktree, a desktop that never published one, or a teardown after
// the route was already taken away by hand.
export async function removeWorktreeRoute(host: string): Promise<boolean> {
  if (!edgeIsOurs()) return false
  const f = routeFile(host)
  if (!existsSync(f)) return false
  rmSync(f, { force: true })
  await reloadCaddy()
  return true
}
