import { execFile, spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { readSupportConfig } from './compose'

// Per-worktree routing on the shared server. The host runs a single Caddy (build
// with the cloudflare DNS plugin) that fronts everything on the Tailscale IP —
// the Rookery UI at `ide.<domain>` and the worktree apps at `<slug>.dev.<domain>`.
// Its Caddyfile (`~/.config/caddy/Caddyfile`) `import`s `sites/*.caddy`, so a
// worktree route is just a file we drop in that dir; `caddy reload` picks it up.
//
// We reuse the host Caddy instead of running our own (it already owns :443 on the
// Tailscale IP with valid wildcard TLS) — see .rookery/plans for the why.
//
// Server-only: on dev machines there is no host Caddy and container mode isn't
// used, so these calls simply fail loudly if ever invoked there.

const SITES_DIR = join(homedir(), '.config', 'caddy', 'sites')
const CADDYFILE = join(homedir(), '.config', 'caddy', 'Caddyfile')

const routeFile = (host: string): string => join(SITES_DIR, `${host}.caddy`)

// `caddy reload` runs in a fresh process, so `{env.CF_API_TOKEN}` in the Caddyfile
// resolves against ITS env — which must carry the token or the cloudflare TLS
// module rejects an empty value and the reload aborts. The running caddy already
// has the token in its environment; read it from there so we don't duplicate the
// secret into support.env. Linux-only (uses /proc); returns '' elsewhere.
function caddyToken(): string {
  const pid = spawnSync('pgrep', ['-x', 'caddy'], { encoding: 'utf8' }).stdout.trim().split('\n')[0]
  if (!pid) return ''
  try {
    const environ = readFileSync(`/proc/${pid}/environ`, 'utf8')
    const hit = environ.split('\0').find((l) => l.startsWith('CF_API_TOKEN='))
    return hit ? hit.slice('CF_API_TOKEN='.length) : ''
  } catch {
    return ''
  }
}

function reloadCaddy(): Promise<void> {
  return new Promise((resolve, reject) => {
    execFile(
      'caddy',
      ['reload', '--config', CADDYFILE],
      { env: { ...process.env, CF_API_TOKEN: caddyToken() } },
      (err, _stdout, stderr) => (err ? reject(new Error(stderr.trim() || err.message)) : resolve())
    )
  })
}

// The Caddyfile block for one worktree app: bind the same IP as the main site
// (else Caddy conflicts on :443), per-site DNS-01 TLS, reverse-proxy to the
// loopback port the app container publishes.
// ponytail: per-site cert means a ~30-60s first-request wait while ACME runs;
// swap for a shared `*.dev` wildcard cert if that latency bites.
function routeBlock(host: string, port: number, bind: string): string {
  return `# Generated by Rookery — worktree app route.
${host} {
	bind ${bind}
	tls {
		dns cloudflare {env.CF_API_TOKEN}
		propagation_delay 30s
		propagation_timeout -1
	}
	reverse_proxy 127.0.0.1:${port}
}
`
}

// Add (or rewrite) the route for a worktree app and reload Caddy. Idempotent.
export async function writeWorktreeRoute(host: string, port: number): Promise<void> {
  mkdirSync(SITES_DIR, { recursive: true })
  writeFileSync(routeFile(host), routeBlock(host, port, readSupportConfig().edgeBind))
  await reloadCaddy()
}

// Remove a worktree's route and reload. No-op if the file/dir isn't there (e.g.
// a host-native worktree, or teardown after the route was never written).
export async function removeWorktreeRoute(host: string): Promise<void> {
  const f = routeFile(host)
  if (!existsSync(f)) return
  rmSync(f, { force: true })
  await reloadCaddy()
}
