// The `floe` command — everything the app side of it needs.
//
// `floe <path>` (bin/floe.mjs) turns a directory into a Floe project and puts
// it on screen. It reaches the app two ways — the loopback control port while
// Floe runs, `--open <path>` on the launch argv when it doesn't — and both land
// in `openProject` here, so the two routes cannot drift apart.
//
// Electron-free on purpose (the paths are passed in, not read off `app`), which
// is what lets the tests drive the real install into a temp home.

import { chmodSync, copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { delimiter, join } from 'node:path'
import { addProjectByPath, renameProject } from './projects'
import type { Project } from '../shared/types'

export interface CliOpen {
  project?: Project
  created?: boolean
  /** What the command prints on success. */
  message?: string
  error?: string
}

/**
 * Register a repository and say what happened, in the words the command prints.
 *
 * Re-adding a project Floe already has is not an error — it is how you bring an
 * existing project forward — so the two cases differ only in the sentence.
 *
 * `name` is the sidebar name (`floe . my-app`). It names a new project and
 * renames an existing one, so the command says what the row reads either way.
 */
export async function openProject(path: string, name?: string): Promise<CliOpen> {
  const added = await addProjectByPath(path)
  if (added.error) return { error: added.error }
  if (!added.project) return { error: `Could not add ${path}.` }
  const root = added.project.path
  const project = name?.trim()
    ? (renameProject(root, name).find((p) => p.path === root) ?? added.project)
    : added.project
  const verb = added.created ? 'Added' : 'Opened'
  return { ...added, project, message: `${verb} ${project.name} — ${project.path}` }
}

/** The `--name <name>` that rides along with `--open`, or null. */
export function openNameFromArgv(argv: string[]): string | null {
  const at = argv.indexOf('--name')
  const value = at === -1 ? null : argv[at + 1]
  return value && !value.startsWith('-') ? value : null
}

/**
 * The `--open <path>` a CLI launch puts on the argv, or null.
 *
 * Scanned rather than indexed: the flag sits at argv[1] in a packaged app and
 * after the app entry in a dev run, and neither position is worth encoding.
 */
export function openPathFromArgv(argv: string[]): string | null {
  const at = argv.indexOf('--open')
  const value = at === -1 ? null : argv[at + 1]
  return value && !value.startsWith('-') ? value : null
}

// --- installing the command -------------------------------------------------
// ⌘K "Install the floe command" writes a shim into ~/.local/bin — no sudo, and
// the same path on macOS and Linux.

const MARKER = '# floe-cli-shim'

/** Where the shim lives. `~/.local/bin` is on PATH for most shells already. */
export const shimPath = (homeDir: string): string => join(homeDir, '.local', 'bin', 'floe')

/**
 * The app's copy of bin/floe.mjs, kept outside the app bundle.
 *
 * The bundle's own path is not stable everywhere a Floe runs — a Linux AppImage
 * mounts its resources at a fresh /tmp path on every launch — so the shim points
 * at a copy under the data dir instead, refreshed at boot (`refreshCli`) so an
 * update ships its new script to an already-installed command.
 */
export const installedScript = (dataDir: string): string => join(dataDir, 'cli', 'floe.mjs')

export function cliShim(exePath: string, scriptPath: string, version: string): string {
  // ELECTRON_RUN_AS_NODE turns the app binary into the node that runs the
  // script, so the command needs no node of its own. FLOE_APP_EXE hands the
  // same binary to the script, which launches it when no Floe is running.
  return `#!/bin/sh
${MARKER} — generated by Floe. Reinstall from ⌘K "Install the floe command".
FLOE_APP_EXE="${exePath}" \\
FLOE_APP_VERSION="${version}" \\
ELECTRON_RUN_AS_NODE=1 \\
exec "${exePath}" "${scriptPath}" "$@"
`
}

export interface CliPaths {
  /** The app binary — `app.getPath('exe')`, or the AppImage that wraps it. */
  exePath: string
  /** bin/floe.mjs as shipped with this build. */
  scriptPath: string
  version: string
  homeDir: string
  dataDir: string
  /** PATH as the user's shell has it, so the message can say what is missing. */
  pathEnv?: string
}

export function installCli(paths: CliPaths): { ok: boolean; message: string; path?: string } {
  const shim = shimPath(paths.homeDir)
  try {
    const script = installedScript(paths.dataDir)
    mkdirSync(join(paths.dataDir, 'cli'), { recursive: true })
    copyFileSync(paths.scriptPath, script)
    mkdirSync(join(paths.homeDir, '.local', 'bin'), { recursive: true })
    writeFileSync(shim, cliShim(paths.exePath, script, paths.version))
    chmodSync(shim, 0o755)
  } catch (e) {
    return { ok: false, message: `Could not write ${shim}: ${(e as Error).message}` }
  }
  const dir = join(paths.homeDir, '.local', 'bin')
  const onPath = (paths.pathEnv ?? '').split(delimiter).includes(dir)
  const hint = onPath ? 'Try: floe .' : `Add ${dir} to your PATH, then: floe .`
  return { ok: true, path: shim, message: `Installed ${shim}. ${hint}` }
}

/**
 * Keep an installed command pointing at this build. Called at boot.
 *
 * Only ever rewrites a shim this app wrote (the marker), and only when it went
 * stale: an update moves the binary and ships a new script, and a command that
 * still execs the old bundle is a command that stopped working.
 */
export function refreshCli(paths: CliPaths): void {
  const shim = shimPath(paths.homeDir)
  if (!existsSync(shim) || !existsSync(paths.scriptPath)) return
  try {
    const current = readFileSync(shim, 'utf8')
    if (!current.includes(MARKER)) return // somebody else's `floe` — leave it alone
    if (current === cliShim(paths.exePath, installedScript(paths.dataDir), paths.version)) {
      // Same shim, but the script behind it may still be the previous build's.
      copyFileSync(paths.scriptPath, installedScript(paths.dataDir))
      return
    }
    installCli(paths)
  } catch {
    // A read-only home, a shim someone chmod'd: the command keeps whatever it
    // had. Never a boot failure.
  }
}
