import { execFile } from 'node:child_process'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { writeWorktreeRoute } from './caddy'
import { readSupportConfig } from './compose'

// The shared "support" stack: ONE MySQL + ONE Postgres + ONE Redis + ONE DBGate
// serving every container-mode worktree on the machine. Provisioning creates a
// database and a Redis key-prefix per worktree inside these (see provision.ts),
// so N dev environments don't mean N database containers.
//
// Edge/TLS is NOT here: the host's own Caddy fronts everything and Floe writes
// per-worktree route files for it (see ./caddy.ts). DBGate and the worktree app
// containers publish loopback ports for it to reach.
//
// The per-worktree PHP/app container is generated per worktree (./compose.ts);
// this file is only the shared infra underneath it.
//
// The compose file is GENERATED into ~/.floe/support rather than shipped as a
// repo asset, for the same reason the per-worktree one is: a packaged Floe keeps
// its files inside app.asar, which `docker compose` cannot read.

export const supportDir = (): string => join(homedir(), '.floe', 'support')
export const supportComposePath = (): string => join(supportDir(), 'docker-compose.yml')
export const supportEnvPath = (): string => join(homedir(), '.floe', 'support.env')

export const SUPPORT_PROJECT = 'floe-support'
/** Loopback port DBGate publishes, for the host Caddy to front at `db.dev.<domain>`. */
export const DBGATE_PORT = 41800

// Interpolated by `docker compose --env-file`, not by us: the passwords stay in
// ~/.floe/support.env (0600) and never land in a world-readable compose file.
export function supportComposeYaml(): string {
  return `# Generated by Floe — do not edit by hand (rewritten on every support up).
name: ${SUPPORT_PROJECT}

services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: \${MYSQL_ROOT_PASSWORD}
    # Published on loopback for host-native fallback + manual admin. Container
    # apps reach it by service name (\`mysql\`) over the shared \`floe\` network.
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - floe
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p\${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 12

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - floe
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 12

  dbgate:
    image: dbgate/dbgate:latest
    restart: unless-stopped
    # Both shared DBs pre-wired, so DBGate opens already connected — no manual login.
    environment:
      CONNECTIONS: con1,con2
      LABEL_con1: MySQL
      SERVER_con1: mysql
      USER_con1: root
      PASSWORD_con1: \${MYSQL_ROOT_PASSWORD}
      PORT_con1: "3306"
      ENGINE_con1: mysql@dbgate-plugin-mysql
      LABEL_con2: Postgres
      SERVER_con2: postgres
      USER_con2: postgres
      PASSWORD_con2: \${POSTGRES_PASSWORD}
      PORT_con2: "5432"
      ENGINE_con2: postgres@dbgate-plugin-postgres
    volumes:
      - dbgate-data:/root/.dbgate
    # Loopback only — the host Caddy reverse-proxies \`db.dev.<domain>\` here.
    ports:
      - "127.0.0.1:${DBGATE_PORT}:3000"
    networks:
      - floe

  # Shared Redis for cache/session/queue across ALL worktrees. Isolation is by a
  # per-worktree key prefix (REDIS_PREFIX, set in provisioning), not by DB index —
  # Redis' 16-DB ceiling doesn't scale to N worktrees. No password: same private
  # \`floe\` network posture as the DBs.
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - floe
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 12

# The network per-worktree app containers join (\`external: true\` on their side,
# see compose.ts). Named explicitly so \`floe-<slug>\` projects find it by name.
networks:
  floe:
    name: floe

volumes:
  mysql-data:
  postgres-data:
  dbgate-data:
  redis-data:
`
}

// Seeded once, then hand-edited. Kept out of the generated compose so a rewrite
// of the stack never clobbers the machine's passwords or domain.
export function supportEnvExample(): string {
  return `# Read by Floe (readSupportConfig) and by \`docker compose --env-file\`.
# Fill this in, then bring the support stack up again.

DOMAIN=pinguim.io

# The IP the host Caddy binds (the server's Tailscale address). Floe writes
# per-worktree route files (src/main/caddy.ts) that must bind the SAME IP as the
# main site, or Caddy fights itself over :443.
EDGE_BIND=100.105.189.56

# DB root credentials. Used by provisioning to create per-worktree databases and
# by DBGate to pre-connect to both engines. A project's .env DB_PASSWORD must
# match these (host-native fallback connects on 127.0.0.1:3306 / :5432).
MYSQL_ROOT_PASSWORD=floe
POSTGRES_PASSWORD=floe

# Note: edge TLS is the HOST Caddy's job (it holds its own CF_API_TOKEN); the
# support stack runs no Caddy, so no Cloudflare token is needed here.
`
}

/**
 * Write the generated compose file and make sure the env file exists. Returns
 * `seeded` when the env file was just created — the caller must stop and let the
 * user fill in the domain/passwords, because `up` with the defaults would bring
 * up a stack nothing else agrees with.
 */
export function ensureSupportFiles(): { seeded: boolean } {
  mkdirSync(supportDir(), { recursive: true })
  writeFileSync(supportComposePath(), supportComposeYaml())
  if (existsSync(supportEnvPath())) return { seeded: false }
  writeFileSync(supportEnvPath(), supportEnvExample(), { mode: 0o600 })
  return { seeded: true }
}

function dockerCompose(args: string[]): Promise<string> {
  return new Promise((resolve, reject) => {
    execFile(
      'docker',
      ['compose', '--project-directory', supportDir(), '-f', supportComposePath(), '--env-file', supportEnvPath(), ...args],
      { maxBuffer: 8 * 1024 * 1024 },
      (err, stdout, stderr) => {
        if (!err) return resolve(stdout.trim() || stderr.trim())
        const detail = stderr.trim() || err.message
        reject(new Error(/ENOENT/.test(detail) ? 'docker not found on this machine' : detail))
      }
    )
  })
}

/** Bring the shared stack up, returning the lines to show the user. */
export async function supportUp(): Promise<string> {
  if (ensureSupportFiles().seeded)
    throw new Error(`Created ${supportEnvPath()} — fill in DOMAIN and the passwords, then run this again`)
  await dockerCompose(['up', '-d'])
  const { domain } = readSupportConfig()
  // DBGate only publishes a loopback port; `db.dev.<domain>` exists solely because
  // we write the route for it. Announcing that URL without creating the route sent
  // the user to a hostname nothing answered — so the route is written here, and on
  // a desktop (where it is a no-op) the loopback address is reported instead.
  const routed = await writeWorktreeRoute(`db.dev.${domain}`, DBGATE_PORT)
  return [
    'Support stack up',
    `  db:       ${routed ? `https://db.dev.${domain} (127.0.0.1:${DBGATE_PORT})` : `http://127.0.0.1:${DBGATE_PORT}`}`,
    '  mysql:    127.0.0.1:3306',
    '  postgres: 127.0.0.1:5432',
    '  redis:    127.0.0.1:6379'
  ].join('\n')
}

export async function supportDown(): Promise<string> {
  await dockerCompose(['down'])
  return 'Support stack down'
}

export async function supportStatus(): Promise<string> {
  if (!existsSync(supportComposePath())) return 'Support stack was never brought up on this machine'
  return (await dockerCompose(['ps'])) || 'Support stack is down'
}

export async function supportLogs(tail = 100): Promise<string> {
  // Same guard as status: without it, asking for logs on a machine that never
  // brought the stack up answers with docker's "couldn't find env file: …",
  // which reads like a broken install rather than "there is nothing here yet".
  if (!existsSync(supportComposePath())) return 'Support stack was never brought up on this machine'
  return (await dockerCompose(['logs', `--tail=${tail}`])) || 'No logs yet'
}

// ⌘K / preload seam. One entry point with an action, mirroring the `support_stack`
// MCP tool exactly, so the palette and an agent run the same code path.
export async function supportStack(action: unknown): Promise<string> {
  try {
    if (action === 'up') return await supportUp()
    if (action === 'down') return await supportDown()
    if (action === 'logs') return await supportLogs()
    return await supportStatus()
  } catch (e) {
    return e instanceof Error ? e.message : String(e)
  }
}
