// Generates src/renderer/src/icons.tsx from Pixelarticons (MIT), keeping the
// export names the renderer already used with Tabler so call sites only swap
// the import. Run: node scripts/gen-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

// Tabler name → Pixelarticons file. One line per icon, so a swap is a diff of one line.
const MAP = {
  Activity: 'analytics',
  AlertCircle: 'alert',
  ArrowBackUp: 'reply',
  ArrowLeft: 'arrow-left',
  ArrowRight: 'arrow-right',
  ArrowUp: 'arrow-up',
  Book: 'book',
  Brackets: 'code',
  BrandDocker: 'ship',
  BrandGit: 'git-commit',
  BrandGolang: 'script',
  BrandPython: 'script',
  CaretRightFilled: 'chevron-right',
  Check: 'check',
  Checklist: 'checklist',
  ChevronDown: 'chevron-down',
  ChevronRight: 'chevron-right',
  Copy: 'copy',
  Database: 'server',
  ExternalLink: 'external-link',
  File: 'file',
  FileDiff: 'track-changes',
  FileText: 'file-alt',
  FileTypeCss: 'paint-bucket',
  FileTypeCsv: 'table',
  FileTypeHtml: 'code',
  FileTypeJs: 'script',
  FileTypePdf: 'file-alt',
  FileTypePhp: 'script',
  FileTypeRs: 'script',
  FileTypeSql: 'table',
  FileTypeTs: 'script',
  FileTypeVue: 'script',
  FileTypeXml: 'code',
  FileZip: 'archive',
  Folder: 'folder',
  Folders: 'folder',
  GitBranch: 'git-branch',
  GitCompare: 'git-pull-request',
  GitMerge: 'git-merge',
  Json: 'script',
  Key: 'label',
  LayoutColumns: 'layout-columns',
  LayoutRows: 'layout-rows',
  License: 'script-text',
  Lock: 'lock',
  Markdown: 'article',
  Menu2: 'menu',
  Message: 'message-text',
  Message2: 'message',
  Movie: 'movie',
  Music: 'music',
  Notes: 'notes',
  Package: 'archive',
  Palette: 'colors-swatch',
  Pencil: 'edit',
  Photo: 'image',
  PlayerPlay: 'play',
  PlayerStop: 'debug-stop',
  PlayerStopFilled: 'debug-stop',
  Plug: 'link',
  Plus: 'plus',
  Puzzle: 'grid',
  QuestionMark: 'info-box',
  Refresh: 'reload',
  Settings: 'sliders',
  Sparkles: 'zap',
  Terminal2: 'code',
  Toml: 'script',
  Tool: 'debug',
  Trash: 'trash',
  UserCircle: 'user',
  Video: 'video',
  World: 'monitor',
  X: 'close'
}

const svgDir = join(process.cwd(), 'node_modules', 'pixelarticons', 'svg')
const paths = (file) => {
  const svg = readFileSync(join(svgDir, `${file}.svg`), 'utf8')
  const out = []
  for (const m of svg.matchAll(/<path\b([^>]*)\/?>/g)) {
    const attrs = m[1]
    const d = /\sd="([^"]+)"/.exec(attrs)?.[1]
    if (!d) continue
    const rule = /fill-rule="([^"]+)"/.exec(attrs)?.[1]
    out.push({ d, rule })
  }
  if (!out.length) throw new Error(`no path in ${file}.svg`)
  return out
}

let body = `// GENERATED by scripts/gen-icons.mjs from pixelarticons ${JSON.parse(readFileSync(join(svgDir, '..', 'package.json'), 'utf8')).version} (MIT). Do not edit.
// The same export names the app used with Tabler, drawn by Pixelarticons: a
// 24-grid of squares, so \`shape-rendering: crispEdges\` keeps them square at
// any size. The \`stroke\` prop is accepted and ignored — these are fills.
import type { ComponentType, SVGProps } from 'react'

export interface IconProps extends Omit<SVGProps<SVGSVGElement>, 'stroke'> {
  size?: number | string
  stroke?: number | string
}
export type Icon = ComponentType<IconProps>

function make(name: string, paths: readonly { d: string; rule?: string }[]): Icon {
  const C: Icon = ({ size = 24, stroke, className, ...rest }) => {
    void stroke
    return (
      <svg
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill="currentColor"
        shapeRendering="crispEdges"
        className={className}
        {...rest}
      >
        {paths.map((p, i) => (
          <path key={i} d={p.d} fillRule={p.rule as 'evenodd' | undefined} clipRule={p.rule as 'evenodd' | undefined} />
        ))}
      </svg>
    )
  }
  C.displayName = name
  return C
}

`
for (const [name, file] of Object.entries(MAP)) {
  const ps = paths(file)
  body += `export const Icon${name} = make('Icon${name}', ${JSON.stringify(ps.map((p) => (p.rule ? p : { d: p.d })))})\n`
}
writeFileSync(join(process.cwd(), 'src', 'renderer', 'src', 'icons.tsx'), body)
console.log(`wrote ${Object.keys(MAP).length} icons`)
